version: 2.1
orbs:
  spruce: sprucelabsai/orb@1
jobs:
  test:
    docker:
      - image: cimg/node:21.7
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ec:9f:2e:aa:1f:c9:ab:49:57:8f:c0:cd:2e:5b:f3:b0"
      - checkout
      - run:
          name: "Check and skip if npm-publish"
          command: |
            COMMIT_MSG=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            if [[ $COMMIT_MSG == *"[npm-publish]"* ]]; then
              echo "[npm-publish] detected. No publish necessary 👊"
              circleci-agent step halt
            fi
      - run: node -v && npm -v && yarn -v
      - run: yarn install
      - run: yarn lint
      - run: yarn build.ci
      - run: yarn test
      - run:
          name: Check branch for auto-upgrade
          command: |
            if [[ ${CIRCLE_BRANCH} != "upgrade-"* ]]; then
              circleci-agent step halt
            fi
      - run:
          name: Merge auto-upgrade into master
          command: |
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
            git fetch --all
            git checkout -f master
            git reset --hard origin/master
            git merge --no-ff ${CIRCLE_BRANCH} -m "chore(auto-upgrade): Upgrade Tests Passed [auto-merge]"
            git push origin
  npm_publish:
    docker:
      - image: cimg/node:21.7
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ec:9f:2e:aa:1f:c9:ab:49:57:8f:c0:cd:2e:5b:f3:b0"
      - checkout
      - spruce/check_and_skip_if_npm_publish
      - spruce/install_rsync
      - spruce/install_deps_build_dist_release
      # - run:
      #     name: Authenticate with registry
      #     command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      # - run: 'npm run publish -- --yes --force-publish --dist-tag latest --message "chore(release): %v [npm-publish]"'
  upgrade:
    docker:
      - image: cimg/node:21.7
    steps:
      - spruce/check_for_autoupgrade_dns
      - add_ssh_keys:
          fingerprints:
            - "ec:9f:2e:aa:1f:c9:ab:49:57:8f:c0:cd:2e:5b:f3:b0"
      - checkout
      - spruce/set_target_branch_env
      - run:
          name: "Try to upgrade"
          command: |
            git checkout -b $TARGETBRANCH || git checkout $TARGETBRANCH
            git reset --hard master
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
            yarn run upgrade.packages.all
            if [[ $(git status) != *"modified"* ]]; then 
              echo "No modifications detected.  No push/PR necessary 👊"
              circleci-agent step halt
            fi
      - spruce/create_pr
workflows:
  version: 2.1
  do_build:
    jobs:
      - test:
          context: public_package_publish
      - npm_publish:
          requires:
            - test
          context: public_package_publish
          filters:
            branches:
              only:
                - master
  upgrade:
    jobs:
      - upgrade:
          context: public_package_publish
          filters:
            branches:
              only:
                - never_run_only_for_cron
